# Candace Savonen Apr 2025

name: Testing ottr-reports
on:
  workflow_dispatch:
  pull_request:
    branches: [ main, dev ]

jobs:
  ottr-reports:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    container:
      image: jhudsl/base_ottr:main


    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Reports
      id: run-reports
      uses: ottrproject/ottr-reports@main
      with:
        check_spelling: TRUE
        spelling_error_min: 1
        check_urls: TRUE
        url_error_min: 1
        check_quiz_form: TRUE
        quiz_error_min: 1
        sort_dictionary: true
